version: '3.4'

services:
  mask-d:
    build: ./
    command: python3 ./encode.py "LogFile/failed-login.log"
    command: python3 ./authenticate.py "LogFileDfs/encoded"
    volumes:
      - ./:/home/richul/Documents/EnhancingMailServerSecurity/Output/

